### ISSUE TITLE
panic error

### ISSUE THREAD

**Issue by trasta298** [21hack02win/nascalay-backend#100]
```
app_1           | {"time":"2021-12-11T09:17:35.4530747Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"OPTIONS","uri":"/rooms/new","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":27320,"latency_human":"27.32��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T09:17:35.467848161Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"POST","uri":"/rooms/new","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":201,"error":"code=201, message={6 6ca1b952-87bd-4470-a075-cabed7616c02 [{{#FEFCC8 0} 6ca1b952-87bd-4470-a075-cabed7616c02 dasda}] sjpDyBlJjy 6ca1b952-87bd-4470-a075-cabed7616c02}","latency":261439,"latency_human":"261.439��s","bytes_in":71,"bytes_out":252}
app_1           | echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
app_1           | {"time":"2021-12-11T09:17:35.531179706Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"GET","uri":"/ws?user=6ca1b952-87bd-4470-a075-cabed7616c02","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":325318,"latency_human":"325.318��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T09:19:14.659408997Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"OPTIONS","uri":"/rooms/join","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36","status":204,"error":"","latency":22520,"latency_human":"22.52��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T09:19:14.674341817Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"POST","uri":"/rooms/join","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36","status":200,"error":"code=200, message={6 6ca1b952-87bd-4470-a075-cabed7616c02 [{{#FEFCC8 0} 6ca1b952-87bd-4470-a075-cabed7616c02 dasda} {{#FFE5BE 0} 205ea5f0-2cdd-470b-ad35-9c001ad5c9bb dawrw}] sjpDyBlJjy 205ea5f0-2cdd-470b-ad35-9c001ad5c9bb}","latency":193199,"latency_human":"193.199��s","bytes_in":80,"bytes_out":359}
app_1           | echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
app_1           | {"time":"2021-12-11T09:19:14.762456503Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"GET","uri":"/ws?user=205ea5f0-2cdd-470b-ad35-9c001ad5c9bb","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36","status":204,"error":"","latency":144480,"latency_human":"144.48��s","bytes_in":0,"bytes_out":0}
app_1           | panic: send on closed channel
app_1           |
app_1           | goroutine 30 [running]:
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendOrUnregister(0x4000106ba0, 0x40000e2c60, {0x4000122050, 0x50, 0x50})
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:145 +0x4c
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendMsgToEachClientInRoom.func1(0x40000e2c60)
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:156 +0x48
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).bloadcast(0x4000106ba0, 0x4000050f80)
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:139 +0xd0
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendMsgToEachClientInRoom(0x4000106ba0, {0x4000122050, 0x50, 0x50})
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:155 +0x64
app_1           | created by github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendGameStartEvent
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/handler.go:168 +0x1c0
```

**Comment by Ras96** [comment]
これあんま自信ないけどあってる？
```go
func (c *Client) sendOrUnregister(cc *Client, msg []byte) {
	select {
	case cc.send <- msg:
	default:
		if cc.userId == c.room.HostId {
			c.sendChangeHostEvent()
		}
		c.hub.unregister(cc)
	}
}
```

**Comment by trasta298** [comment]
```
app_1           | {"time":"2021-12-11T10:14:30.425966746Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"GET","uri":"/ws?user=83561311-cd3e-4b89-a8d4-c9035da70e88","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":173760,"latency_human":"173.76��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T10:15:15.403901855Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"OPTIONS","uri":"/rooms/join","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":26720,"latency_human":"26.72��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T10:15:15.418688677Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"POST","uri":"/rooms/join","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":200,"error":"code=200, message={6 83561311-cd3e-4b89-a8d4-c9035da70e88 [{{#53E520 0} 83561311-cd3e-4b89-a8d4-c9035da70e88 1} {{#8F8A0B 0} 0ebea54c-c1c8-42f6-9464-1729ccb1e23b 2}] nwZS4R7qJr 0ebea54c-c1c8-42f6-9464-1729ccb1e23b}","latency":98360,"latency_human":"98.36��s","bytes_in":76,"bytes_out":351}
app_1           | echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
app_1           | {"time":"2021-12-11T10:15:15.492070747Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"GET","uri":"/ws?user=0ebea54c-c1c8-42f6-9464-1729ccb1e23b","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":113399,"latency_human":"113.399��s","bytes_in":0,"bytes_out":0}
app_1           | {"time":"2021-12-11T10:15:17.147698341Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"POST","uri":"/rooms/join","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":200,"error":"code=200, message={6 83561311-cd3e-4b89-a8d4-c9035da70e88 [{{#53E520 0} 83561311-cd3e-4b89-a8d4-c9035da70e88 1} {{#8F8A0B 0} 0ebea54c-c1c8-42f6-9464-1729ccb1e23b 2} {{#FFE5BE 0} 6e032b65-c2ac-42d2-ada0-50a07a3e428e 3}] nwZS4R7qJr 6e032b65-c2ac-42d2-ada0-50a07a3e428e}","latency":93320,"latency_human":"93.32��s","bytes_in":76,"bytes_out":454}
app_1           | echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
app_1           | {"time":"2021-12-11T10:15:17.220349814Z","id":"","remote_ip":"106.73.13.226","host":"api.nascalay.trasta.dev","method":"GET","uri":"/ws?user=6e032b65-c2ac-42d2-ada0-50a07a3e428e","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43","status":204,"error":"","latency":122679,"latency_human":"122.679��s","bytes_in":0,"bytes_out":0}
app_1           | panic: send on closed channel
app_1           |
app_1           | goroutine 85 [running]:
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendOrUnregister(0x40001ba8a0, 0x40001bac60, {0x4000082a80, 0x53, 0x60})
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:145 +0x4c
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendMsgToEachClientInRoom.func1(0x40001bac60)
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:156 +0x48
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).bloadcast(0x40001ba8a0, 0x4000052f80)
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:139 +0xd0
app_1           | github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendMsgToEachClientInRoom(0x40001ba8a0, {0x4000082a80, 0x53, 0x60})
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/client.go:155 +0x64
app_1           | created by github.com/21hack02win/nascalay-backend/usecases/service/ws.(*Client).sendGameStartEvent
app_1           |       /go/src/github.com/21hack02win/nascalay-backend/usecases/service/ws/handler.go:168 +0x1c0
```

**Comment by trasta298** [comment]
ゲームスタートを押したとき

**Comment by Ras96** [comment]
#105
